'use client'

import { AlertCircle, CheckCircle2, AlertTriangle, Share2, Download, Copy, Check } from 'lucide-react'
import Image from 'next/image'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { DiseaseProbabilityChart } from './disease-probability-chart'
import type { AnalysisResult } from '@/types'
import { useState } from 'react'

interface AnalysisCardData extends Pick<AnalysisResult, 
  'plantType' | 'healthStatus' | 'disease' | 'confidence' | 'recommendation' | 'diseaseProbs' | 'llmDescription'
> {
  plantImage?: string
}

const getStatusConfig = (status: 'healthy' | 'stressed' | 'diseased') => {
  switch (status) {
    case 'healthy':
      return {
        color: 'text-primary',
        bgSubtle: 'bg-primary/10',
        borderSubtle: 'border-primary/20',
        icon: CheckCircle2,
        label: 'Healthy',
      }
    case 'stressed':
      return {
        color: 'text-amber-700 dark:text-amber-400',
        bgSubtle: 'bg-amber-50 dark:bg-amber-950/20',
        borderSubtle: 'border-amber-200 dark:border-amber-800/30',
        icon: AlertTriangle,
        label: 'Stressed',
      }
    case 'diseased':
      return {
        color: 'text-destructive',
        bgSubtle: 'bg-destructive/10',
        borderSubtle: 'border-destructive/20',
        icon: AlertCircle,
        label: 'Disease Detected',
      }
  }
}

export function AnalysisCard({ data }: { data: AnalysisCardData }) {
  const statusConfig = getStatusConfig(data.healthStatus)
  const StatusIcon = statusConfig.icon
  const [copied, setCopied] = useState(false)

  const generateReportText = () => {
    const lines = [
      `Zali Plant Analysis Report`,
      `========================`,
      ``,
      `Plant: ${data.plantType}`,
      `Status: ${statusConfig.label}`,
      `Confidence: ${Math.round(data.confidence * 100)}%`,
      data.disease ? `Detected Issue: ${data.disease}` : '',
      ``,
      `Analysis:`,
      data.llmDescription || data.recommendation,
      ``,
      `Generated by Zali`,
      `Date: ${new Date().toLocaleDateString()}`,
    ].filter(Boolean)
    
    return lines.join('\n')
  }

  const handleCopyToClipboard = async () => {
    const reportText = generateReportText()
    await navigator.clipboard.writeText(reportText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownloadReport = () => {
    const reportText = generateReportText()
    const blob = new Blob([reportText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `zali-report-${data.plantType.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleShare = async () => {
    const reportText = generateReportText()
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Zali Analysis: ${data.plantType}`,
          text: reportText,
        })
      } catch {
        handleCopyToClipboard()
      }
    } else {
      handleCopyToClipboard()
    }
  }

  return (
    <Card>
      <CardHeader className="p-6 pb-4">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <StatusIcon className={`h-4 w-4 ${statusConfig.color}`} aria-hidden="true" />
              <span className={`text-xs font-medium ${statusConfig.color}`}>
                {statusConfig.label}
              </span>
            </div>
            <CardTitle className="text-xl">{data.plantType}</CardTitle>
          </div>
          <div className="flex items-center gap-3">
            <div className="text-right">
              <p className="text-xs text-muted-foreground mb-1">Confidence</p>
              <p className="text-2xl font-semibold text-foreground">
                {Math.round(data.confidence * 100)}%
              </p>
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button 
                  variant="ghost" 
                  size="icon"
                  className="text-muted-foreground hover:text-foreground"
                  aria-label="Share or export report"
                >
                  <Share2 className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-48">
                <DropdownMenuItem onClick={handleShare} className="gap-2 cursor-pointer">
                  <Share2 className="h-4 w-4" />
                  Share Report
                </DropdownMenuItem>
                <DropdownMenuItem onClick={handleCopyToClipboard} className="gap-2 cursor-pointer">
                  {copied ? (
                    <>
                      <Check className="h-4 w-4 text-primary" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="h-4 w-4" />
                      Copy to Clipboard
                    </>
                  )}
                </DropdownMenuItem>
                <DropdownMenuItem onClick={handleDownloadReport} className="gap-2 cursor-pointer">
                  <Download className="h-4 w-4" />
                  Download Report
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-4 px-6 pb-6">
        {data.plantImage && (
          <div className="overflow-hidden rounded-lg">
            <Image
              src={data.plantImage}
              alt={`Analyzed ${data.plantType}`}
              width={800}
              height={224}
              className="h-56 w-full object-cover"
              unoptimized
            />
          </div>
        )}

        <div className="grid gap-4">
          {data.disease && (
            <div className={`rounded-lg ${statusConfig.bgSubtle} border ${statusConfig.borderSubtle} p-4`}>
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                Detected Issue
              </p>
              <p className="mt-2 text-sm font-medium text-foreground">
                {data.disease}
              </p>
            </div>
          )}

          <div className="rounded-lg border border-border bg-muted/50 p-4">
            <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
              AI Analysis
            </p>
            <p className="mt-2 text-sm leading-relaxed text-foreground">
              {data.llmDescription || data.recommendation}
            </p>
          </div>
        </div>

        {data.diseaseProbs && data.diseaseProbs.length > 0 && (
          <div className="rounded-lg border border-border p-4">
            <DiseaseProbabilityChart diseaseProbs={data.diseaseProbs} plantType={data.plantType} />
          </div>
        )}
      </CardContent>
    </Card>
  )
}
